from pathlib import Path
import json
import pandas as pd,numpy as np
import matplotlib.pyplot as plt,seaborn as sns
from matplotlib.path import Path as MPath
from matplotlib.patches import PathPatch
ROOT=Path(__file__).resolve().parent.parent;STEP=Path(__file__).resolve().parent;OUT=STEP/'results_v1';TAB=OUT/'tables';FIG=OUT/'figures';META=OUT/'metadata'
rank=pd.read_csv(ROOT/'step6_drug_link_v1/results/drug_link_out_v1/tables/state5_integrated_drug_ranking_v1.tsv',sep='\t')
names=['bisindolylmaleimide','CPI-613','picolinic-acid','moxonidine','teriflunomide','rottlerin','trifluoperazine','selumetinib','trametinib','gemcitabine']
d=rank[rank.pert_iname.isin(names)].copy()
audit={
'bisindolylmaleimide':dict(identity='Unresolved BRD-K31342827 screening reagent',mechanism='Do not assign: class members differ in PKC and transporter activity',direct_oscc='None located',combination='No compound-specific cisplatin evidence located',negative='Exact structure and target unresolved',maximum_claim='Three-screen computational hit requiring identity resolution',pmids='26657401|17575116'),
'CPI-613':dict(identity='Devimistat; lipoate analogue',mechanism='Mitochondrial pyruvate- and α-ketoglutarate-dehydrogenase perturbation',direct_oscc='No direct OSCC validation located',combination='Preclinical synergy with gemcitabine/cisplatin in biliary cancer',negative='Phase III pancreatic and AML trials did not establish benefit',maximum_claim='Leading dual-transcriptomic predicted sensitizer',pmids='37115501|39088774|40454396'),
'picolinic-acid':dict(identity='Picolinic acid',mechanism='Metal-chelating metabolite; mechanism not established here',direct_oscc='None located',combination='None located',negative='Weak PRISM depletion and no frozen-axis top-decile support',maximum_claim='Secondary state-5/PRISM hypothesis',pmids=''),
'moxonidine':dict(identity='Moxonidine',mechanism='Imidazoline/adrenergic receptor agonist',direct_oscc='None located',combination='None located',negative='No PRISM evidence',maximum_claim='Dual-transcriptomic hypothesis only',pmids=''),
'teriflunomide':dict(identity='Teriflunomide',mechanism='Dihydroorotate dehydrogenase inhibitor',direct_oscc='None located in this audit',combination='No direct cisplatin-resensitization evidence verified',negative='No PRISM evidence',maximum_claim='Dual-transcriptomic hypothesis only',pmids=''),
'rottlerin':dict(identity='Rottlerin',mechanism='Pleiotropic mitochondrial/kinase probe; not a selective PKCδ inhibitor',direct_oscc='None verified',combination='None verified',negative='Mechanistically promiscuous; no PRISM evidence',maximum_claim='Low-specificity transcriptomic hypothesis',pmids=''),
'trifluoperazine':dict(identity='Trifluoperazine',mechanism='Dopamine-receptor antagonist with calmodulin-related effects',direct_oscc='None verified',combination='No direct OSCC cisplatin evidence verified',negative='No PRISM evidence',maximum_claim='Dual-transcriptomic hypothesis only',pmids=''),
'selumetinib':dict(identity='Selumetinib',mechanism='MEK1/2 inhibitor',direct_oscc='No state-specific validation',combination='Mechanistic relevance possible, not validated by this study',negative='No matched PRISM support in current screen',maximum_claim='Dual-transcriptomic hypothesis only',pmids=''),
'trametinib':dict(identity='Trametinib',mechanism='MEK1/2 inhibitor',direct_oscc='No state-specific validation',combination='Mechanistic relevance possible, not validated by this study',negative='No matched PRISM support in current screen',maximum_claim='Dual-transcriptomic hypothesis only',pmids=''),
'gemcitabine':dict(identity='Gemcitabine',mechanism='Antimetabolite/nucleoside analogue',direct_oscc='Not a state-specific OSCC sensitization result',combination='Established chemotherapy; state-5 LINCS-only signal here',negative='Absent from independent frozen-axis table and current PRISM match',maximum_claim='State-5 reversal control/hypothesis',pmids='')}
for c in ['identity','mechanism','direct_oscc','combination','negative','maximum_claim','pmids']:d[c]=d.pert_iname.map(lambda x:audit[x][c])
d['identity_resolved']=~d.pert_iname.eq('bisindolylmaleimide');d['direct_OSCC_cisplatin_evidence']=False;d['PRISM_depletion']=d.PRISM_supported;d['dual_transcriptomic']=d.frozen_axis_top10pct;d['state5_robust']=d.state5_robust
d=d.sort_values(['evidence_count','state5_rank'],ascending=[False,True]);d.to_csv(TAB/'candidate_evidence_audit_v1.tsv',sep='\t',index=False)
refs=pd.DataFrame([
[1,37115501,'10.1158/1078-0432.CCR-22-3505','Devimistat with gemcitabine and cisplatin in biliary tract cancer','CPI-613 combination precedent; different cancer'],[2,39088774,'10.1200/JCO.23.02659','AVENGER 500 phase III study','Negative phase III evidence for devimistat'],[3,40454396,'','ARMADA phase III trial','Negative/limiting phase III evidence for devimistat'],[4,26657401,'10.1371/journal.pone.0144667','PKC-independent transporter effects of Ro 31-8220','Chemical-class caution; not identity proof'],[5,17575116,'10.1158/1535-7163.MCT-06-0811','ABCG2 inhibition by bisindolylmaleimides','Chemical-class transporter evidence; not identity proof'],[6,29523854,'','Cisplatin oxidative stress and carbon metabolism in HNSCC','HNSCC metabolic rationale'],[7,31534516,'','Mitochondrial metabolism and cisplatin resistance in tongue SCC','OSCC/TSCC metabolic rationale'],[8,38164660,'10.1002/hed.27620','ATP7B and extracellular-vesicle cisplatin resistance in HNSCC','Direct disease-context resistance biology']
],columns=['citation_order','pmid','doi','title','supported_use']);refs.to_csv(TAB/'verified_candidate_references_v1.tsv',sep='\t',index=False)

sns.set_theme(style='white',font_scale=.86);fig,axs=plt.subplots(2,3,figsize=(14.2,9.2),constrained_layout=True)
def panel(ax,l,t):ax.text(-.12,1.07,l,transform=ax.transAxes,fontweight='bold',fontsize=14,va='top');ax.set_title(t,loc='left',fontweight='bold',fontsize=10)
ax=axs[0,0];panel(ax,'a','Evidence-gated candidate funnel');ax.axis('off');items=[('1,750','LINCS compounds'),('328','Robust state-5'),('43','Orthogonal support'),('2','PRISM support'),('1','Three-screen hit')];
for i,(n,t) in enumerate(items):
 y=.92-i*.18;w=.92-i*.14;ax.add_patch(plt.Rectangle(((1-w)/2,y-.11),w,.13,color=sns.color_palette('Blues',6)[i+1],alpha=.9));ax.text(.5,y-.045,f'{n}  {t}',ha='center',va='center',color='white' if i>1 else 'black',fontweight='bold',fontsize=8)
ax=axs[0,1];panel(ax,'b','Quantitative evidence for shortlisted drugs');show=d.head(10);x=np.arange(len(show));ax.scatter(x,show.state5_percentile,label='State-5 percentile',s=35);ax.scatter(x,1-show.frozen_axis_rank/1750,label='Frozen-axis percentile',s=35);ax.scatter(x,np.where(show.PRISM_supported,np.clip(-show.prism_uadt_median_LFC,0,1),np.nan),label='PRISM depletion',s=35);ax.set_xticks(x,show.pert_iname,rotation=65,ha='right',fontsize=6);ax.set_ylim(0,1.05);ax.set_ylabel('Evidence metric (0–1)');ax.legend(frameon=False,fontsize=6)
ax=axs[0,2];panel(ax,'c','Independent evidence matrix');em=show.set_index('pert_iname')[['identity_resolved','state5_robust','dual_transcriptomic','PRISM_depletion','direct_OSCC_cisplatin_evidence']].astype(float);sns.heatmap(em,cmap=sns.color_palette(['#F2F2F2','#228833'],as_cmap=True),vmin=0,vmax=1,cbar=False,linewidths=.5,ax=ax);ax.set_xticklabels(['Identity','State-5','Frozen axis','PRISM','Direct OSCC'],rotation=25,ha='right');ax.set_ylabel('')
ax=axs[1,0];panel(ax,'d','Cross-cell-line state-5 reversal');z=show.sort_values('state5_reversal');y=np.arange(len(z));ax.hlines(y,z.q25,z.q75,color='#999999');ax.scatter(z.state5_reversal,y,c=np.where(z.PRISM_supported,'#D55E00','#0072B2'),s=30);ax.axvline(0,c='k',lw=.7);ax.set_yticks(y,z.pert_iname,fontsize=7);ax.set_xlabel('LINCS median reversal (IQR)')
ax=axs[1,1];panel(ax,'e','Mechanistic program–candidate map');ax.axis('off');progs=['Mitochondrial\nmetabolism','UPR / stress','Drug transport','MAPK signaling'];drugs=['CPI-613','Bisindolylmaleimide*','Selumetinib','Trametinib'];links=[(0,0,.95),(1,0,.45),(2,1,.55),(3,2,.8),(3,3,.8)]
for i,p in enumerate(progs):ax.text(.1,.85-i*.22,p,ha='center',va='center',fontsize=7,bbox=dict(boxstyle='round',fc='#56B4E9',alpha=.75))
for j,p in enumerate(drugs):ax.text(.9,.85-j*.22,p,ha='center',va='center',fontsize=7,bbox=dict(boxstyle='round',fc='#E69F00',alpha=.75))
for i,j,w in links:path=MPath([(.2,.85-i*.22),(.45,.85-i*.22),(.55,.85-j*.22),(.8,.85-j*.22)],[MPath.MOVETO,MPath.CURVE4,MPath.CURVE4,MPath.CURVE4]);ax.add_patch(PathPatch(path,facecolor='none',edgecolor='#7A5195',lw=1+4*w,alpha=.25+.5*w))
ax.text(.5,.02,'*Exact bisindolylmaleimide structure unresolved',ha='center',fontsize=6)
ax=axs[1,2];panel(ax,'f','Claim ceiling after literature audit');ax.axis('off');lines=[('CPI-613','Leading predicted sensitizer','No direct OSCC evidence; phase III failures elsewhere'),('Bisindolylmaleimide','Unresolved three-screen hit','Resolve exact structure before mechanism/lab work'),('Picolinic acid','Secondary computational hypothesis','Weak PRISM depletion; no direct evidence')]
for i,(n,c,l) in enumerate(lines):y=.88-i*.29;ax.text(.02,y,n,fontweight='bold',fontsize=9);ax.text(.02,y-.08,c,color='#0072B2',fontsize=8);ax.text(.02,y-.16,l,color='#555555',fontsize=7,wrap=True)
fig.suptitle('Evidence audit separates computational convergence from validated sensitization',fontweight='bold',fontsize=15)
fig.savefig(FIG/'Figure_candidate_audit_v1.png',dpi=300,bbox_inches='tight');fig.savefig(FIG/'Figure_candidate_audit_v1.pdf',bbox_inches='tight');fig.savefig(FIG/'Figure_candidate_audit_v1.tif',dpi=600,bbox_inches='tight',pil_kwargs={'compression':'tiff_lzw'});plt.close(fig)
summary={'recommended_lead':'CPI-613 (devimistat): strongest state-specific and frozen-axis reversal, but no direct OSCC or current PRISM validation','identity_hold':'BRD-K31342827: do not assign a specific bisindolylmaleimide structure or mechanism','secondary':'picolinic acid: weak state-5/PRISM hypothesis','directly_validated_sensitizers':0,'claim':'Computationally prioritized candidates for experimental cisplatin-combination testing.'};(META/'summary_v1.json').write_text(json.dumps(summary,indent=2)+'\n')
